-- public.simple_notes definition

-- Drop table

-- DROP TABLE public.simple_notes;

CREATE TABLE public.simple_notes (
	id int4 NOT NULL DEFAULT nextval('notes_id_seq'::regclass),
	title varchar NULL,
	note varchar NOT NULL,
	CONSTRAINT notes_pk PRIMARY KEY (id)
);

INSERT INTO public.simple_notes (title,note) VALUES
	 ('title','another note'),
	 ('test','another one'),
	 ('','note'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.');
INSERT INTO public.simple_notes (title,note) VALUES
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.'),
	 ('Lorem Ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo sem diam, nec sagittis neque maximus in. In molestie enim vel dui tristique, sit amet vestibulum urna cursus. Ut ut commodo elit, id hendrerit justo. Praesent sodales justo erat, a mollis libero facilisis in. Mauris nulla magna, finibus et purus scelerisque, placerat vehicula dui. Morbi vestibulum nisi massa, eu laoreet sem hendrerit vel. Ut congue lacinia posuere. Ut non rhoncus magna. Curabitur laoreet nunc at nisl tincidunt, sit amet tempus nisl vestibulum. Duis lobortis, nibh id dapibus efficitur, turpis ante interdum felis, a congue lectus velit eget velit. Cras sagittis dapibus urna et euismod. Quisque rhoncus mauris vel tellus convallis lacinia. Proin dictum orci sed placerat viverra. Mauris velit erat, consequat et ligula sed, pulvinar eleifend orci.

Aliquam pharetra felis nec purus vulputate pulvinar. In ut ante in ante tempor vulputate nec vitae dolor. Vivamus lobortis purus imperdiet odio efficitur maximus. Vestibulum pharetra, mauris sed finibus molestie, neque dui tincidunt lorem, at congue leo ligula non enim. Nulla quis odio ligula. Aliquam ac tempus metus. Vestibulum suscipit odio ut urna semper, a viverra justo congue. In sit amet ultrices lorem. Curabitur scelerisque posuere consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus euismod pellentesque consectetur. Praesent congue dui non felis dapibus efficitur a id purus. Fusce sit amet dui mauris.');
